spring:
  datasource:
    url: jdbc:mysql://ip주소:port번호/DB이름?characterEncoding=utf8
    username: 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: kr.co.fastcampus.eatgo
  mapper-locations: mybatis/mapper/**/*.xml