#server
server: 
  port: 80

#spring
spring: 
  datasource:
    url: jdbc:mysql://ec2-13-125-149-76.ap-northeast-2.compute.amazonaws.com:3306/ranchat?characterEncoding=utf8
    username: ranchat
    password: R@nchat
    driver-class-name: org.h2.Driver
  mvc: 
    static-path-pattern: /static/**
  resources: 
    static-locations: classpath:/static/
    add-mappings: true
    
    
#redis
redis: 
#  host: ec2-13-125-149-76.ap-northeast-2.compute.amazonaws.com
  host: localhost
  port: 6379
  password: redis