server:
  port: 2500
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ranchat?characterEncoding=utf8
    username: ranchat
    password: R@nchat
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
    add-mappings: true
redis:
  host: localhost
  port: 6379
  password: redis